"""empty message

Revision ID: 25a170105ce1
Revises: 9c94684c1532
Create Date: 2021-03-06 15:49:36.698333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a170105ce1'
down_revision = '9c94684c1532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ser_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_answer_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_answer_ser_id_user'), 'user', ['ser_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), server_default=sa.text("'1'"), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_answer_ser_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_answer_user_id_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('ser_id')

    # ### end Alembic commands ###
